# Generated by Django 6.0 on 2026-01-16 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='is_warden_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warden',
            name='leave_balance',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.worker'),
        ),
    ]
