# Generated by Django 6.0 on 2026-01-10 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('supplier_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='universityid',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('warden', 'Warden'), ('worker', 'Worker'), ('supplier', 'Supplier')], max_length=20),
        ),
        migrations.AlterField(
            model_name='universityid',
            name='university_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('warden', 'Warden'), ('worker', 'Worker'), ('supplier', 'Supplier')], max_length=20),
        ),
        migrations.CreateModel(
            name='Warden',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('warden_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=10)),
                ('admin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_wardens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('worker_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=150)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_workers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
