# Generated by Django 6.0 on 2026-01-10 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_supplier_alter_universityid_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warden',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='contact',
        ),
        migrations.AddField(
            model_name='worker',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='warden',
            name='admin_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_wardens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='worker',
            name='admin_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_workers', to=settings.AUTH_USER_MODEL),
        ),
    ]
