# Generated by Django 6.0 on 2026-01-16 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_leaverequest_is_warden_request_warden_leave_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='admin_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_workers', to=settings.AUTH_USER_MODEL),
        ),
    ]
