# Generated by Django 6.0 on 2026-01-17 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_worker_admin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='warden',
            name='admin_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_wardens', to=settings.AUTH_USER_MODEL),
        ),
    ]
