# Generated by Django 6.0 on 2026-01-11 19:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_warden_contact_remove_worker_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10)),
                ('warden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.warden')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.worker')),
            ],
            options={
                'unique_together': {('worker', 'date')},
            },
        ),
    ]
