# Generated by Django 5.2.9 on 2026-03-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_warden_admin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
