# Generated by Django 6.0 on 2026-01-11 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_attendance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='worker_master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.universityid'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='worker',
        ),
    ]
