# Generated by Django 5.2.9 on 2026-03-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_worker_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='warden',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
