# Generated by Django 6.0 on 2026-01-14 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('worker_master', 'date')},
        ),
    ]
