# Generated by Django 6.0 on 2026-01-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_attendance_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('item_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('item_name', models.CharField(max_length=100)),
                ('current_stock', models.FloatField(default=0.0)),
                ('required_stock', models.FloatField(default=0.0)),
                ('unit', models.CharField(default='kg', max_length=10)),
                ('is_delivered', models.BooleanField(default=False)),
            ],
        ),
    ]
