# Generated by Django 6.0 on 2026-01-15 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_attendance_unique_together'),
        ('accounts', '0007_inventory'),
    ]

    operations = [
    ]
