# Generated by Django 5.2.9 on 2026-03-12 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_supplier_email_warden_email_worker_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='contact',
            new_name='phone',
        ),
    ]
